<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Faisal Saimeh">

<title>Performance Analysis Between CPU and GPU for Machine Learning</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Project_Faisal_Saimeh_files/libs/clipboard/clipboard.min.js"></script>
<script src="Project_Faisal_Saimeh_files/libs/quarto-html/quarto.js"></script>
<script src="Project_Faisal_Saimeh_files/libs/quarto-html/popper.min.js"></script>
<script src="Project_Faisal_Saimeh_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Project_Faisal_Saimeh_files/libs/quarto-html/anchor.min.js"></script>
<link href="Project_Faisal_Saimeh_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Project_Faisal_Saimeh_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Project_Faisal_Saimeh_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Project_Faisal_Saimeh_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Project_Faisal_Saimeh_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="Project_Faisal_Saimeh_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="Project_Faisal_Saimeh_files/libs/plotly-binding-4.10.3/plotly.js"></script>
<script src="Project_Faisal_Saimeh_files/libs/typedarray-0.1/typedarray.min.js"></script>
<script src="Project_Faisal_Saimeh_files/libs/jquery-3.5.1/jquery.min.js"></script>
<link href="Project_Faisal_Saimeh_files/libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="Project_Faisal_Saimeh_files/libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="Project_Faisal_Saimeh_files/libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="Project_Faisal_Saimeh_files/libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Performance Analysis Between CPU and GPU for Machine Learning</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Faisal Saimeh </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="introduction" class="level1">
<h1>Introduction</h1>
<div data-align="justify">
<p>In the realm of machine learning, the selection of appropriate hardware plays a pivotal role in attaining peak performance and efficiency. Among the primary computing devices utilized for machine learning tasks, GPUs and CPUs stand out, each showcasing distinct strengths and weaknesses.</p>
<p>Traditionally, CPUs or central processing units have held the preference owing to their versatility and adeptness in multitasking. CPU acts as the computer’s brain, executing fundamental instructions such as arithmetic, logic operations, and I/O tasks. On the other hand, a GPU, or graphics processing unit, designed originally for 2D and 3D graphics and specialized in rendering for high-resolution graphics, but these days with the surge in big data and machine learning applications has propelled GPUs into the spotlight, given their capacity to manage extensive datasets and execute parallel computations.</p>
<p>This project aims to delve into the variances between GPU and CPU performance by delving into the specifications of the processors, to determine which company and which processors of CPU or GPU provide superior power for machine learning.</p>
</div>
</section>
<section id="about-the-dataset" class="level1">
<h1>About The Dataset</h1>
<div data-align="justify">
<p>This dataset contains 2,185 CPUs and 2,668 GPUs to understand the development trend of CPUs and GPUs and their performance. It encompasses a diverse set of benchmarks and metrics like process size, thermal design power(TDP), die size, number of transistors, and frequency to evaluate the performance of these two types of processors. In addition, the release date and the manufacturer to see the evolution of these processors’ performance during these years.</p>
<section id="important-terminology" class="level2">
<h2 class="anchored" data-anchor-id="important-terminology">Important Terminology:</h2>
<ul>
<li><p><strong>Process Size (nm):</strong> the size of the transistors used in a processor. The size plays a significant role and typically enables a greater number of transistors to be accommodated within the same physical area (Die Area), potentially leading to enhanced performance, decreased power consumption, and reduced production expenses(nm is an acronym for Nano-meter. It is used to measure microscopic objects or devices like transistors found in processors or atomic structures).</p></li>
<li><p><strong>Die Size (mm^2):</strong> In computing, die refers to the piece of silicon of which the processing unit (a GPU or CPU) consists, often called a chip. Die size means the size of the chunk on a silicon wafer that belongs to one chip. Smaller die sizes allow for more transistors to be packed into the same area resulting in higher processing power and also consuming less power. The number and density of transistors packed into the die determine the processor’s computational capacity. (mm^2 is a short form for square millimeters).</p></li>
<li><p><strong>TDP(W):</strong> the electrical energy usage of a computer chip operating at its maximum theoretical load, measured in watts (W).</p></li>
<li><p><strong>Transistors (million):</strong> are minuscule electronic components, that function as switches governing the flow of electricity within a circuit. Within processor architecture, these transistors serve as the foundational elements for constructing logic gates and memory cells, essential components that constitute a processor.</p></li>
<li><p><strong>Freq (MHz):</strong> relates to the clock rate or clock speed at which a processor’s clock generator can produce pulses to perform operations within a specified time frame, which is the responsibility of the billions of transistors within the processor to produce these pulses. For instance, a processor operating at a clock speed of 3.2 GHz (3200 MHz) completes 3.2 billion cycles per second.</p></li>
</ul>
</section>
</div>
</section>
<section id="reading-the-dataset" class="level1">
<h1>Reading The Dataset</h1>
<p>The following code will import the dataset file called “chip_dataset.csv”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"chip_dataset.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To view all dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data_befor <span class="ot">=</span> data</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">data.frame</span>(data_befor))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X                 Product Type Release.Date Process.Size..nm. TDP..W.
1 0     AMD Athlon 64 3500+  CPU    2/20/2007                65      45
2 1        AMD Athlon 200GE  CPU     9/6/2018                14      35
3 2    Intel Core i5-1145G7  CPU     9/2/2020                10      28
4 3   Intel Xeon E5-2603 v2  CPU     9/1/2013                22      80
5 4 AMD Phenom II X4 980 BE  CPU     5/3/2011                45     125
6 5   Intel Xeon E5-2470 v2  CPU     9/1/2013                22      95
  Die.Size..mm.2. Transistors..million. Freq..MHz. Foundry Vendor FP16.GFLOPS
1              77                   122       2200 Unknown    AMD          NA
2             192                  4800       3200 Unknown    AMD          NA
3              NA                    NA       2600   Intel  Intel          NA
4             160                  1400       1800   Intel  Intel          NA
5             258                   758       3700 Unknown    AMD          NA
6             160                  1400       2400   Intel  Intel          NA
  FP32.GFLOPS FP64.GFLOPS
1          NA          NA
2          NA          NA
3          NA          NA
4          NA          NA
5          NA          NA
6          NA          NA</code></pre>
</div>
</div>
</section>
<section id="setting-up-the-libraries" class="level1">
<h1>Setting up the Libraries</h1>
<p>Before we start the analysis, we should first load the essential libraries that we might use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'plotly' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggplot2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'plotly'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:ggplot2':

    last_plot</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:stats':

    filter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:graphics':

    layout</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'data.table'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:dplyr':

    between, first, last</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(grid)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lubridate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:data.table':

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    date, intersect, setdiff, union</code></pre>
</div>
</div>
</section>
<section id="data-cleaning-and-processing" class="level1">
<h1>Data Cleaning and Processing</h1>
<p>This stage is considered a fundamental stage in data analysis because when working with a real-world problem, there is no documentation of the data and the dataset is messy. To improve the quality of the data and to make it more suitable for analysis we have to clean the data by identifying and correcting or removing errors, inconsistencies, and missing values from a dataset and then preprocessing to transform and prepare the data for visualization.</p>
<section id="explore-the-data" class="level2">
<h2 class="anchored" data-anchor-id="explore-the-data">Explore the Data:</h2>
<p>Using the summary function to get overall summary of the dataset. It will return mean, median,25th and 75th quartiles,min and max.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="fu">summary</span>(data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Var1                  Var2                Freq
1                           X      Min.   :   0  
2                           X      1st Qu.:1213  
3                           X      Median :2426  
4                           X      Mean   :2426  
5                           X      3rd Qu.:3640  
6                           X      Max.   :4853  
7                           X                &lt;NA&gt;
8                     Product  Length:4854       
9                     Product  Class :character  
10                    Product  Mode  :character  
11                    Product                &lt;NA&gt;
12                    Product                &lt;NA&gt;
13                    Product                &lt;NA&gt;
14                    Product                &lt;NA&gt;
15                       Type  Length:4854       
16                       Type  Class :character  
17                       Type  Mode  :character  
18                       Type                &lt;NA&gt;
19                       Type                &lt;NA&gt;
20                       Type                &lt;NA&gt;
21                       Type                &lt;NA&gt;
22               Release.Date  Length:4854       
23               Release.Date  Class :character  
24               Release.Date  Mode  :character  
25               Release.Date                &lt;NA&gt;
26               Release.Date                &lt;NA&gt;
27               Release.Date                &lt;NA&gt;
28               Release.Date                &lt;NA&gt;
29          Process.Size..nm.    Min.   :  0.00  
30          Process.Size..nm.    1st Qu.: 22.00  
31          Process.Size..nm.    Median : 40.00  
32          Process.Size..nm.    Mean   : 55.11  
33          Process.Size..nm.    3rd Qu.: 90.00  
34          Process.Size..nm.    Max.   :250.00  
35          Process.Size..nm.         NA's   :9  
36                    TDP..W.    Min.   :  1.00  
37                    TDP..W.    1st Qu.: 33.00  
38                    TDP..W.    Median : 65.00  
39                    TDP..W.    Mean   : 81.36  
40                    TDP..W.    3rd Qu.:100.00  
41                    TDP..W.    Max.   :900.00  
42                    TDP..W.       NA's   :626  
43            Die.Size..mm.2.     Min.   :  1.0  
44            Die.Size..mm.2.     1st Qu.:104.0  
45            Die.Size..mm.2.     Median :148.0  
46            Die.Size..mm.2.     Mean   :188.4  
47            Die.Size..mm.2.     3rd Qu.:239.0  
48            Die.Size..mm.2.     Max.   :826.0  
49            Die.Size..mm.2.       NA's   :715  
50      Transistors..million.     Min.   :    8  
51      Transistors..million.     1st Qu.:  154  
52      Transistors..million.     Median :  624  
53      Transistors..million.     Mean   : 1930  
54      Transistors..million.     3rd Qu.: 1550  
55      Transistors..million.     Max.   :54200  
56      Transistors..million.       NA's   :711  
57                 Freq..MHz.      Min.   : 100  
58                 Freq..MHz.      1st Qu.: 590  
59                 Freq..MHz.      Median :1074  
60                 Freq..MHz.      Mean   :1484  
61                 Freq..MHz.      3rd Qu.:2400  
62                 Freq..MHz.      Max.   :4700  
63                 Freq..MHz.                &lt;NA&gt;
64                    Foundry  Length:4854       
65                    Foundry  Class :character  
66                    Foundry  Mode  :character  
67                    Foundry                &lt;NA&gt;
68                    Foundry                &lt;NA&gt;
69                    Foundry                &lt;NA&gt;
70                    Foundry                &lt;NA&gt;
71                     Vendor  Length:4854       
72                     Vendor  Class :character  
73                     Vendor  Mode  :character  
74                     Vendor                &lt;NA&gt;
75                     Vendor                &lt;NA&gt;
76                     Vendor                &lt;NA&gt;
77                     Vendor                &lt;NA&gt;
78                FP16.GFLOPS Min.   :    10.02  
79                FP16.GFLOPS 1st Qu.:   768.80  
80                FP16.GFLOPS Median :  2965.50  
81                FP16.GFLOPS Mean   :  8397.46  
82                FP16.GFLOPS 3rd Qu.: 10600.00  
83                FP16.GFLOPS Max.   :184600.00  
84                FP16.GFLOPS      NA's   :4318  
85                FP32.GFLOPS   Min.   :   12.8  
86                FP32.GFLOPS   1st Qu.:  257.3  
87                FP32.GFLOPS   Median :  696.0  
88                FP32.GFLOPS   Mean   : 2134.8  
89                FP32.GFLOPS   3rd Qu.: 2116.8  
90                FP32.GFLOPS   Max.   :40000.0  
91                FP32.GFLOPS      NA's   :2906  
92                FP64.GFLOPS  Min.   :    3.60  
93                FP64.GFLOPS  1st Qu.:   38.30  
94                FP64.GFLOPS  Median :   89.28  
95                FP64.GFLOPS  Mean   :  363.67  
96                FP64.GFLOPS  3rd Qu.:  220.00  
97                FP64.GFLOPS  Max.   :11540.00  
98                FP64.GFLOPS      NA's   :3548  </code></pre>
</div>
</div>
</section>
<section id="check-and-handling-missing-valuesdrop-and-rename-columns" class="level2">
<h2 class="anchored" data-anchor-id="check-and-handling-missing-valuesdrop-and-rename-columns">Check and Handling Missing Values,Drop and Rename Columns :</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># To calculate the number of missing values in every column.</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="fu">colSums</span>(<span class="fu">is.na</span>(data)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      colSums.is.na.data..
X                                        0
Product                                  0
Type                                     0
Release.Date                             0
Process.Size..nm.                        9
TDP..W.                                626
Die.Size..mm.2.                        715
Transistors..million.                  711
Freq..MHz.                               0
Foundry                                  0
Vendor                                   0
FP16.GFLOPS                           4318
FP32.GFLOPS                           2906
FP64.GFLOPS                           3548</code></pre>
</div>
</div>
<p>Two ways to handle the missing values drop rows with missing values or replace them with the mean or mode.</p>
<section id="drop-columns" class="level3">
<h3 class="anchored" data-anchor-id="drop-columns">Drop Columns :</h3>
<p>The columns FP16, FP32, and FP64 GFLOPS have too many missing values especially if they do have not any value to CPU only for GPU which is significant for comparing them, and for the Foundry column, also has many missing values as well, and since we have a Vendor column which is kind of the same info present it for us to use. finally, dropping column X because it does not add any value to our data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">select</span>(data, <span class="sc">-</span>X,<span class="sc">-</span>Foundry,<span class="sc">-</span>FP16.GFLOPS,<span class="sc">-</span>FP32.GFLOPS,<span class="sc">-</span>FP64.GFLOPS)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Product Type Release.Date Process.Size..nm. TDP..W.
1     AMD Athlon 64 3500+  CPU    2/20/2007                65      45
2        AMD Athlon 200GE  CPU     9/6/2018                14      35
3    Intel Core i5-1145G7  CPU     9/2/2020                10      28
4   Intel Xeon E5-2603 v2  CPU     9/1/2013                22      80
5 AMD Phenom II X4 980 BE  CPU     5/3/2011                45     125
6   Intel Xeon E5-2470 v2  CPU     9/1/2013                22      95
  Die.Size..mm.2. Transistors..million. Freq..MHz. Vendor
1              77                   122       2200    AMD
2             192                  4800       3200    AMD
3              NA                    NA       2600  Intel
4             160                  1400       1800  Intel
5             258                   758       3700    AMD
6             160                  1400       2400  Intel</code></pre>
</div>
</div>
</section>
<section id="rename-columns" class="level3">
<h3 class="anchored" data-anchor-id="rename-columns">Rename Columns :</h3>
<p>We need to rename the columns to make it easier and more clear when calling them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Product"</span>,<span class="st">"Type"</span>, <span class="st">"Release Date"</span>, <span class="st">"Process Size (nm)"</span>, <span class="st">"TDP (W)"</span>, <span class="st">"Die Size (mm^2)"</span>, <span class="st">"Transistors (million)"</span>, <span class="st">"Frequency (GHz)"</span>, <span class="st">"Company"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Product Type Release Date Process Size (nm) TDP (W)
1     AMD Athlon 64 3500+  CPU    2/20/2007                65      45
2        AMD Athlon 200GE  CPU     9/6/2018                14      35
3    Intel Core i5-1145G7  CPU     9/2/2020                10      28
4   Intel Xeon E5-2603 v2  CPU     9/1/2013                22      80
5 AMD Phenom II X4 980 BE  CPU     5/3/2011                45     125
6   Intel Xeon E5-2470 v2  CPU     9/1/2013                22      95
  Die Size (mm^2) Transistors (million) Frequency (GHz) Company
1              77                   122            2200     AMD
2             192                  4800            3200     AMD
3              NA                    NA            2600   Intel
4             160                  1400            1800   Intel
5             258                   758            3700     AMD
6             160                  1400            2400   Intel</code></pre>
</div>
</div>
<p>In this step, renaming the unit name of the frequency from megahertz to gigahertz because we are dealing with frequencies of modern processors. In the next step, we will change the unit from megahertz to gigahertz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Changing from Mega to Giga / 1 GHZ = 1000 MHZ</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span><span class="st">`</span><span class="at">Frequency (GHz)</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">round</span>(data<span class="sc">$</span><span class="st">`</span><span class="at">Frequency (GHz)</span><span class="st">`</span> <span class="sc">/</span> <span class="dv">1000</span>,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="handling-the-missing-values" class="level3">
<h3 class="anchored" data-anchor-id="handling-the-missing-values">Handling the Missing Values :</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># To calculate the number of missing values in every column agian.</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="fu">colSums</span>(<span class="fu">is.na</span>(data)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      colSums.is.na.data..
Product                                  0
Type                                     0
Release Date                             0
Process Size (nm)                        9
TDP (W)                                626
Die Size (mm^2)                        715
Transistors (million)                  711
Frequency (GHz)                          0
Company                                  0</code></pre>
</div>
</div>
<p>Since the total missing is around 30% so we have to use the replacing missing values. To use this method missing data should be numeric or categorical value data for replacing them with the mean or mode.</p>
<p>I have decided to proceed with the mean solution to replace the missing values. To fill the missing values by mean, I had to take the average separately for each of these columns (TDP (W), Die Size (mm^2), Transistors (million)) grouped by type of processor (CPU, GPU) to make it more accurate.</p>
<p><strong>TDP (W)</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Take the average of TDP (W) grouped by Type and put it in a variable.</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>TDP_AVG <span class="ot">=</span> data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Type) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">avg_tdp =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">TDP (W)</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>TDP_AVG</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  Type  avg_tdp
  &lt;chr&gt;   &lt;dbl&gt;
1 CPU      75.4
2 GPU      87.8</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create variable to take the CPU (TDP (W)) average only.</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>cpu_tdp <span class="ot">=</span> TDP_AVG <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Type <span class="sc">==</span> <span class="st">"CPU"</span>) <span class="sc">%&gt;%</span> pull</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>cpu_tdp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 75.40237</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create variable to take the GPU (TDP (W)) average only.</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>gpu_tdp <span class="ot">=</span> TDP_AVG <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Type <span class="sc">==</span> <span class="st">"GPU"</span>) <span class="sc">%&gt;%</span> pull</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>gpu_tdp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 87.77407</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace missing values with the group mean (TDP (W)) of each type of processor.</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> data <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="st">`</span><span class="at">TDP (W)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(<span class="st">`</span><span class="at">TDP (W)</span><span class="st">`</span>) <span class="sc">&amp;</span> Type <span class="sc">==</span><span class="st">'CPU'</span>, cpu_tdp, <span class="fu">ifelse</span>(<span class="fu">is.na</span>(<span class="st">`</span><span class="at">TDP (W)</span><span class="st">`</span>) <span class="sc">&amp;</span> Type <span class="sc">==</span><span class="st">'GPU'</span>, gpu_tdp , <span class="st">`</span><span class="at">TDP (W)</span><span class="st">`</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the missing value for the column TDP (W) again.</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="fu">colSums</span>(<span class="fu">is.na</span>(data)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      colSums.is.na.data..
Product                                  0
Type                                     0
Release Date                             0
Process Size (nm)                        9
TDP (W)                                  0
Die Size (mm^2)                        715
Transistors (million)                  711
Frequency (GHz)                          0
Company                                  0</code></pre>
</div>
</div>
<p><strong>Die Size (mm^2)</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Take the average of Die Size (mm^2) grouped by Type and put it in a variable.</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>Die_AVG <span class="ot">=</span> data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Type) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">avg_die =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Die Size (mm^2)</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>Die_AVG</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  Type  avg_die
  &lt;chr&gt;   &lt;dbl&gt;
1 CPU      167.
2 GPU      203.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create variable to take the CPU (Die Size (mm^2)) average only.</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>cpu_die <span class="ot">=</span> Die_AVG <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Type <span class="sc">==</span> <span class="st">"CPU"</span>) <span class="sc">%&gt;%</span> pull </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>cpu_die</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 166.506</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create variable to take the GPU Die Size (mm^2) average only.</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>gpu_die <span class="ot">=</span> Die_AVG <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Type <span class="sc">==</span> <span class="st">"GPU"</span>) <span class="sc">%&gt;%</span> pull </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>gpu_die</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 203.1283</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace missing values with the group mean (Die Size (mm^2)) of each type of processor</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> data <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Die Size (mm^2)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(<span class="st">`</span><span class="at">Die Size (mm^2)</span><span class="st">`</span>) <span class="sc">&amp;</span> Type <span class="sc">==</span><span class="st">'CPU'</span>, cpu_die,<span class="fu">ifelse</span>(<span class="fu">is.na</span>(<span class="st">`</span><span class="at">Die Size (mm^2)</span><span class="st">`</span>) <span class="sc">&amp;</span> Type <span class="sc">==</span><span class="st">'GPU'</span>, gpu_die , <span class="st">`</span><span class="at">Die Size (mm^2)</span><span class="st">`</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the missing value for the column Die Size (mm^2) again </span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="fu">colSums</span>(<span class="fu">is.na</span>(data)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      colSums.is.na.data..
Product                                  0
Type                                     0
Release Date                             0
Process Size (nm)                        9
TDP (W)                                  0
Die Size (mm^2)                          0
Transistors (million)                  711
Frequency (GHz)                          0
Company                                  0</code></pre>
</div>
</div>
<p><strong>Transistors (million)</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Take the average of Transistors (million) grouped by Type and put it in a variable.</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>TS_AVG <span class="ot">=</span> data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Type) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">avg_ts =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Transistors (million)</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) </span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>TS_AVG</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  Type  avg_ts
  &lt;chr&gt;  &lt;dbl&gt;
1 CPU    1156.
2 GPU    2455.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create variable to take the CPU (Transistors (million)) average only.</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>cpu_ts <span class="ot">=</span> TS_AVG <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Type <span class="sc">==</span> <span class="st">"CPU"</span>) <span class="sc">%&gt;%</span> pull </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>cpu_ts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1156.34</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create variable to take the GPU (Transistors (million)) average only.</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>gpu_ts <span class="ot">=</span> TS_AVG <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Type <span class="sc">==</span> <span class="st">"GPU"</span>) <span class="sc">%&gt;%</span> pull </span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>gpu_ts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2454.942</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace missing values with the group mean (Transistors (million)) of each type of processor</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> data <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Transistors (million)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(<span class="st">`</span><span class="at">Transistors (million)</span><span class="st">`</span>) <span class="sc">&amp;</span> Type <span class="sc">==</span><span class="st">'CPU'</span>, cpu_ts, <span class="fu">ifelse</span>(<span class="fu">is.na</span>(<span class="st">`</span><span class="at">Transistors (million)</span><span class="st">`</span>) <span class="sc">&amp;</span> Type <span class="sc">==</span><span class="st">'GPU'</span>, gpu_ts , <span class="st">`</span><span class="at">Transistors (million)</span><span class="st">`</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the missing value for the column Transistors (million) again </span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="fu">colSums</span>(<span class="fu">is.na</span>(data)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      colSums.is.na.data..
Product                                  0
Type                                     0
Release Date                             0
Process Size (nm)                        9
TDP (W)                                  0
Die Size (mm^2)                          0
Transistors (million)                    0
Frequency (GHz)                          0
Company                                  0</code></pre>
</div>
</div>
<p><strong>Delete Rows</strong></p>
<p>The remaining nine missing values are too small to affect the data, so the best way to handle them is by dropping these rows by the drop_na function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The last check on missing values in the data set:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="fu">colSums</span>(<span class="fu">is.na</span>(data)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      colSums.is.na.data..
Product                                  0
Type                                     0
Release Date                             0
Process Size (nm)                        0
TDP (W)                                  0
Die Size (mm^2)                          0
Transistors (million)                    0
Frequency (GHz)                          0
Company                                  0</code></pre>
</div>
</div>
</section>
<section id="check-dataset-format" class="level3">
<h3 class="anchored" data-anchor-id="check-dataset-format">Check Dataset Format :</h3>
<p>We need check the dataset format before proceeding to Data Visualization and Analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   4845 obs. of  9 variables:
 $ Product              : chr  "AMD Athlon 64 3500+" "AMD Athlon 200GE" "Intel Core i5-1145G7" "Intel Xeon E5-2603 v2" ...
 $ Type                 : chr  "CPU" "CPU" "CPU" "CPU" ...
 $ Release Date         : chr  "2/20/2007" "9/6/2018" "9/2/2020" "9/1/2013" ...
 $ Process Size (nm)    : int  65 14 10 22 45 22 65 65 10 90 ...
 $ TDP (W)              : num  45 35 28 80 125 95 125 130 28 89 ...
 $ Die Size (mm^2)      : num  77 192 167 160 258 ...
 $ Transistors (million): num  122 4800 1156 1400 758 ...
 $ Frequency (GHz)      : num  2.2 3.2 2.6 1.8 3.7 2.4 2.4 3 2 2.2 ...
 $ Company              : chr  "AMD" "AMD" "Intel" "Intel" ...</code></pre>
</div>
</div>
<p>All the columns are in suitable format except the Release Date column formatted as a character, formatting it to date using as.Date function is to make it easier when we look for trends over time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Release Date</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">as.Date</span>(<span class="st">`</span><span class="at">Release Date</span><span class="st">`</span>,<span class="at">format =</span> <span class="fu">c</span>(<span class="st">"%m/%d/%Y"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check again all the formats</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   4845 obs. of  9 variables:
 $ Product              : chr  "AMD Athlon 64 3500+" "AMD Athlon 200GE" "Intel Core i5-1145G7" "Intel Xeon E5-2603 v2" ...
 $ Type                 : chr  "CPU" "CPU" "CPU" "CPU" ...
 $ Release Date         : Date, format: "2007-02-20" "2018-09-06" ...
 $ Process Size (nm)    : int  65 14 10 22 45 22 65 65 10 90 ...
 $ TDP (W)              : num  45 35 28 80 125 95 125 130 28 89 ...
 $ Die Size (mm^2)      : num  77 192 167 160 258 ...
 $ Transistors (million): num  122 4800 1156 1400 758 ...
 $ Frequency (GHz)      : num  2.2 3.2 2.6 1.8 3.7 2.4 2.4 3 2 2.2 ...
 $ Company              : chr  "AMD" "AMD" "Intel" "Intel" ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check NA </span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="fu">colSums</span>(<span class="fu">is.na</span>(data)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      colSums.is.na.data..
Product                                  0
Type                                     0
Release Date                            72
Process Size (nm)                        0
TDP (W)                                  0
Die Size (mm^2)                          0
Transistors (million)                    0
Frequency (GHz)                          0
Company                                  0</code></pre>
</div>
</div>
<p>After formatting the date, we explore more NA values in the date column, and because the number is too small to affect, we will drop these rows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, we need to check if there are any zero values in our dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="fu">colSums</span>(data<span class="sc">==</span><span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      colSums.data....0.
Product                                0
Type                                   0
Release Date                           0
Process Size (nm)                      4
TDP (W)                                0
Die Size (mm^2)                        0
Transistors (million)                  0
Frequency (GHz)                        0
Company                                0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Viewing the product that has zero processor</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(data,data<span class="sc">$</span><span class="st">`</span><span class="at">Process Size (nm)</span><span class="st">`</span> <span class="sc">==</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Product Type Release Date Process Size (nm)  TDP (W)
2235 Matrox QID LP PCIe  GPU   2004-12-17                 0 87.77407
3365     Matrox QID PRO  GPU   2004-12-17                 0 87.77407
3831         Matrox QID  GPU   2004-12-17                 0 87.77407
4190  Matrox QID LP PCI  GPU   2004-12-17                 0 87.77407
     Die Size (mm^2) Transistors (million) Frequency (GHz) Company
2235        203.1283              2454.942             0.2   Other
3365        203.1283              2454.942             0.2   Other
3831        203.1283              2454.942             0.2   Other
4190        203.1283              2454.942             0.2   Other</code></pre>
</div>
</div>
<p>There is something wrong with these products information, they have the same values in all columns even though they are different products. The optimal solution is to drop these rows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">subset</span>(data, data<span class="sc">$</span><span class="st">`</span><span class="at">Process Size (nm)</span><span class="st">`</span> <span class="sc">!=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="add-column" class="level3">
<h3 class="anchored" data-anchor-id="add-column">Add Column :</h3>
<p>The last step in Data Cleaning and Processing is to creating new column called Transistor Density to calculate the number of transistors per square millimeter on a chip.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'Transistor Density'</span>]<span class="ot">&lt;-</span> <span class="fu">round</span>((data[<span class="st">'Transistors (million)'</span>] <span class="sc">*</span> <span class="dv">1000000</span>) <span class="sc">/</span> data[<span class="st">'Die Size (mm^2)'</span>], <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Viewing the data after Data Cleaning and Processing</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>data_after <span class="ot">=</span> data</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">data.frame</span>(data_after))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Product Type Release.Date Process.Size..nm. TDP..W.
1     AMD Athlon 64 3500+  CPU   2007-02-20                65      45
2        AMD Athlon 200GE  CPU   2018-09-06                14      35
3    Intel Core i5-1145G7  CPU   2020-09-02                10      28
4   Intel Xeon E5-2603 v2  CPU   2013-09-01                22      80
5 AMD Phenom II X4 980 BE  CPU   2011-05-03                45     125
6   Intel Xeon E5-2470 v2  CPU   2013-09-01                22      95
  Die.Size..mm.2. Transistors..million. Frequency..GHz. Company
1          77.000                122.00             2.2     AMD
2         192.000               4800.00             3.2     AMD
3         166.506               1156.34             2.6   Intel
4         160.000               1400.00             1.8   Intel
5         258.000                758.00             3.7     AMD
6         160.000               1400.00             2.4   Intel
  Transistor.Density
1            1584416
2           25000000
3            6944736
4            8750000
5            2937985
6            8750000</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="data-visualization-and-analysis" class="level1">
<h1>Data Visualization and Analysis</h1>
<p>Data visualization is the graphical representation of a dataset in a pictorial format. It is a way to see and understand trends, patterns in data, and outliers. Data visualization is essential to the Analysis for discovering useful information and making findings.</p>
<section id="count-types-of-processors" class="level2">
<h2 class="anchored" data-anchor-id="count-types-of-processors"><strong>Count Types of Processors</strong></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>data_for_plot <span class="ot">=</span>  data <span class="sc">%&gt;%</span> <span class="fu">count</span>(Type,<span class="at">name=</span><span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>legend_labels <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="fu">names</span>(data_for_plot<span class="sc">$</span>Count),data_for_plot<span class="sc">$</span>Type ,<span class="st">": "</span>, data_for_plot<span class="sc">$</span>Count)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>legend_labels</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] " CPU :  2189" " GPU :  2580"</code></pre>
</div>
</div>
<section id="total-processors-count" class="level3">
<h3 class="anchored" data-anchor-id="total-processors-count"><strong>Total Processors Count</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>custom_colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#ffa500"</span>, <span class="st">"#0a75ad"</span>)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_ly</span>(data_for_plot, <span class="at">labels =</span> <span class="sc">~</span>Type, <span class="at">values =</span> <span class="sc">~</span>Count, <span class="at">type =</span> <span class="st">'pie'</span>,<span class="at">textinfo =</span> <span class="st">'label+percent'</span>, <span class="at">insidetextorientation =</span> <span class="st">'radial'</span>,<span class="at">marker =</span> <span class="fu">list</span>(<span class="at">colors =</span> custom_colors)) <span class="sc">%&gt;%</span>  <span class="fu">layout</span>(<span class="at">title =</span> <span class="fu">list</span>(<span class="at">text =</span> <span class="st">"CPU vs GPU Count Unit"</span>, <span class="at">x =</span> <span class="fl">0.5</span>,<span class="at">y =</span> <span class="fl">0.98</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-ca2e186fdab2c59b5b6f" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-ca2e186fdab2c59b5b6f">{"x":{"visdat":{"474350dd6d":["function () ","plotlyVisDat"]},"cur_data":"474350dd6d","attrs":{"474350dd6d":{"labels":{},"values":{},"textinfo":"label+percent","insidetextorientation":"radial","marker":{"colors":["#ffa500","#0a75ad"]},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"pie"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":{"text":"CPU vs GPU Count Unit","x":0.5,"y":0.97999999999999998},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"labels":["CPU","GPU"],"values":[2189,2580],"textinfo":"label+percent","insidetextorientation":"radial","marker":{"color":"rgba(31,119,180,1)","colors":["#ffa500","#0a75ad"],"line":{"color":"rgba(255,255,255,1)"}},"type":"pie","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<div data-align="justify">
<p>In this graph, we can see in the provided bar graph that we slightly have more GPUs than CPUs that we’ll deal with. We can say that we have a pretty balanced amount of data for both processing units, in which GPUs have 2580 units and CPUs have 2189 units.</p>
</div>
</section>
</section>
<section id="the-development-of-cpus-and-gpus-over-years" class="level2">
<h2 class="anchored" data-anchor-id="the-development-of-cpus-and-gpus-over-years"><strong>The Development of CPUs and GPUs Over Years</strong></h2>
<section id="average-process-size" class="level3">
<h3 class="anchored" data-anchor-id="average-process-size"><strong>Average Process Size</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(<span class="at">Year =</span> <span class="fu">as.numeric</span>(<span class="fu">format</span>(<span class="st">`</span><span class="at">Release Date</span><span class="st">`</span>, <span class="st">'%Y'</span>)), <span class="st">`</span><span class="at">Process Size (nm)</span><span class="st">`</span>, Type) <span class="sc">%&gt;%</span></span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Type) <span class="sc">%&gt;%</span></span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_count =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Process Size (nm)</span><span class="st">`</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Year'. You can override using the
`.groups` argument.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(result, <span class="fu">aes</span>(<span class="at">x =</span>Year, <span class="at">y =</span> mean_count, <span class="at">color =</span> Type)) <span class="sc">+</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#0a75ad"</span>,<span class="st">"#ff4040"</span>)) <span class="sc">+</span></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(</span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">2000</span>,<span class="dv">2002</span>,<span class="dv">2004</span>,<span class="dv">2006</span>,<span class="dv">2008</span>,<span class="dv">2010</span>,<span class="dv">2012</span>,<span class="dv">2014</span>,<span class="dv">2016</span>,<span class="dv">2018</span>,<span class="dv">2020</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="dv">2000</span>,<span class="dv">2002</span>,<span class="dv">2004</span>,<span class="dv">2006</span>,<span class="dv">2008</span>,<span class="dv">2010</span>,<span class="dv">2012</span>,<span class="dv">2014</span>,<span class="dv">2016</span>,<span class="dv">2018</span>,<span class="dv">2020</span>))<span class="sc">+</span></span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">20</span>,<span class="dv">40</span>,<span class="dv">60</span>,<span class="dv">80</span>,<span class="dv">100</span>,<span class="dv">120</span>,<span class="dv">140</span>,<span class="dv">160</span>,<span class="dv">180</span>,<span class="dv">200</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="dv">20</span>,<span class="dv">40</span>,<span class="dv">60</span>,<span class="dv">80</span>,<span class="dv">100</span>,<span class="dv">120</span>,<span class="dv">140</span>,<span class="dv">160</span>,<span class="dv">180</span>,<span class="dv">200</span>))<span class="sc">+</span></span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">" Average Process Size (nm) Over Years"</span>, <span class="at">x =</span> <span class="st">"Release Date"</span>, <span class="at">y =</span> <span class="st">"Process Size (nm)"</span>)<span class="sc">+</span></span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Project_Faisal_Saimeh_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div data-align="justify">
<p>The Process Size for CPU and GPU evolved similarly with no significant distinction between the two. When we get a closer look at the decade (2000-2010) witness tremendous development compared to the period that followed 2010. However, the overall trend is on consistent decrease in Process Size over time. That is a sign of the integration of more advanced technologies, enabling to achievement of smaller Process Sizes to enhance performance.</p>
</div>
</section>
<section id="average-transistors" class="level3">
<h3 class="anchored" data-anchor-id="average-transistors"><strong>Average Transistors</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>result2 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(<span class="at">Year =</span> <span class="fu">as.numeric</span>(<span class="fu">format</span>(<span class="st">`</span><span class="at">Release Date</span><span class="st">`</span>, <span class="st">'%Y'</span>)), <span class="st">`</span><span class="at">Transistors (million)</span><span class="st">`</span>, Type) <span class="sc">%&gt;%</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Type) <span class="sc">%&gt;%</span></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_count =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Transistors (million)</span><span class="st">`</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Year'. You can override using the
`.groups` argument.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(result2, <span class="fu">aes</span>(<span class="at">x =</span>Year, <span class="at">y =</span> mean_count, <span class="at">color =</span> Type)) <span class="sc">+</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#0a75ad"</span>,<span class="st">"#ff4040"</span>)) <span class="sc">+</span></span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(</span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">2000</span>,<span class="dv">2002</span>,<span class="dv">2004</span>,<span class="dv">2006</span>,<span class="dv">2008</span>,<span class="dv">2010</span>,<span class="dv">2012</span>,<span class="dv">2014</span>,<span class="dv">2016</span>,<span class="dv">2018</span>,<span class="dv">2020</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="dv">2000</span>,<span class="dv">2002</span>,<span class="dv">2004</span>,<span class="dv">2006</span>,<span class="dv">2008</span>,<span class="dv">2010</span>,<span class="dv">2012</span>,<span class="dv">2014</span>,<span class="dv">2016</span>,<span class="dv">2018</span>,<span class="dv">2020</span>))<span class="sc">+</span></span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">1000</span>,<span class="dv">2500</span>,<span class="dv">5000</span>,<span class="dv">7500</span>,<span class="dv">10000</span>,<span class="dv">12500</span>,<span class="dv">15000</span>,<span class="dv">17000</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="dv">1000</span>,<span class="dv">2500</span>,<span class="dv">5000</span>,<span class="dv">7500</span>,<span class="dv">10000</span>,<span class="dv">12500</span>,<span class="dv">15000</span>,<span class="dv">17000</span>))<span class="sc">+</span></span>
<span id="cb89-9"><a href="#cb89-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">" Average Transistors (million) Over Years"</span>, <span class="at">x =</span> <span class="st">"Release Date"</span>, <span class="at">y =</span> <span class="st">"Transistors (million)"</span>)<span class="sc">+</span></span>
<span id="cb89-10"><a href="#cb89-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Project_Faisal_Saimeh_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div data-align="justify">
<p>For the number of Transistors able to be fit in the processors, we can observe an upward trend indicating for both CPU and GPU from 2008 to 2018, then we have an observable decline in the period between 2018 and 2019 for CPUs and then a slight increase, unlike GPUs have a slight decrease but in 2016 had a massive increase for Transistors numbers. The reason GPUs have more transistors than CPUs, they are hugely different in architecture. CPU is designed with very few cores, but very powerful cores that are extremely complex and can handle all sorts of tasks and complex processes. A GPU is basically designed for parallel computing, to handle parallel processing tasks efficiently, particularly for graphics rendering and parallelizable computing workloads such as hose found in machine learning, and that’s the reason why GPU is more powerful in machine learning. And despite that, GPUs have thousands of cores but they are much less powerful than those on a CPU.</p>
</div>
</section>
<section id="average-frequency" class="level3">
<h3 class="anchored" data-anchor-id="average-frequency"><strong>Average Frequency</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>result3 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(<span class="at">Year =</span> <span class="fu">as.numeric</span>(<span class="fu">format</span>(<span class="st">`</span><span class="at">Release Date</span><span class="st">`</span>, <span class="st">'%Y'</span>)), <span class="st">`</span><span class="at">Frequency (GHz)</span><span class="st">`</span>, Type) <span class="sc">%&gt;%</span></span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Type) <span class="sc">%&gt;%</span></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_count =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Frequency (GHz)</span><span class="st">`</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Year'. You can override using the
`.groups` argument.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(result3, <span class="fu">aes</span>(<span class="at">x =</span>Year, <span class="at">y =</span> mean_count, <span class="at">color =</span> Type)) <span class="sc">+</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#0a75ad"</span>,<span class="st">"#ff4040"</span>)) <span class="sc">+</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(</span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">2000</span>,<span class="dv">2002</span>,<span class="dv">2004</span>,<span class="dv">2006</span>,<span class="dv">2008</span>,<span class="dv">2010</span>,<span class="dv">2012</span>,<span class="dv">2014</span>,<span class="dv">2016</span>,<span class="dv">2018</span>,<span class="dv">2020</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="dv">2000</span>,<span class="dv">2002</span>,<span class="dv">2004</span>,<span class="dv">2006</span>,<span class="dv">2008</span>,<span class="dv">2010</span>,<span class="dv">2012</span>,<span class="dv">2014</span>,<span class="dv">2016</span>,<span class="dv">2018</span>,<span class="dv">2020</span>))<span class="sc">+</span></span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">" Average Frequency (GHz) Over Years"</span>, <span class="at">x =</span> <span class="st">"Release Date"</span>, <span class="at">y =</span> <span class="st">"Frequency (GHz)"</span>)<span class="sc">+</span></span>
<span id="cb92-8"><a href="#cb92-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Project_Faisal_Saimeh_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div data-align="justify">
<p>Looking at this graph for the Frequencies, we can see the big difference in performance between CPUs compared to GPUs with clear superiority CPUs over GPUs. However, both Processing unit seems to have had good development over the years, but the GPUs’ improvement is more consistent than the CPUs. Perhaps on this level, GPUs will outperform CPUs in the future in Frequencies.</p>
</div>
</section>
<section id="average-die-size" class="level3">
<h3 class="anchored" data-anchor-id="average-die-size"><strong>Average Die Size</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>result4 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(<span class="at">Year =</span> <span class="fu">as.numeric</span>(<span class="fu">format</span>(<span class="st">`</span><span class="at">Release Date</span><span class="st">`</span>, <span class="st">'%Y'</span>)), <span class="st">`</span><span class="at">Die Size (mm^2)</span><span class="st">`</span>, Type) <span class="sc">%&gt;%</span></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Type) <span class="sc">%&gt;%</span></span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_count =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Die Size (mm^2)</span><span class="st">`</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Year'. You can override using the
`.groups` argument.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(result4, <span class="fu">aes</span>(<span class="at">x =</span>Year, <span class="at">y =</span> mean_count, <span class="at">color =</span> Type)) <span class="sc">+</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#0a75ad"</span>,<span class="st">"#ff4040"</span>)) <span class="sc">+</span></span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(</span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">2000</span>,<span class="dv">2002</span>,<span class="dv">2004</span>,<span class="dv">2006</span>,<span class="dv">2008</span>,<span class="dv">2010</span>,<span class="dv">2012</span>,<span class="dv">2014</span>,<span class="dv">2016</span>,<span class="dv">2018</span>,<span class="dv">2020</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="dv">2000</span>,<span class="dv">2002</span>,<span class="dv">2004</span>,<span class="dv">2006</span>,<span class="dv">2008</span>,<span class="dv">2010</span>,<span class="dv">2012</span>,<span class="dv">2014</span>,<span class="dv">2016</span>,<span class="dv">2018</span>,<span class="dv">2020</span>))<span class="sc">+</span></span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb95-8"><a href="#cb95-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">100</span>,<span class="dv">150</span>,<span class="dv">200</span>,<span class="dv">250</span>,<span class="dv">300</span>,<span class="dv">350</span>,<span class="dv">400</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="dv">100</span>,<span class="dv">150</span>,<span class="dv">200</span>,<span class="dv">250</span>,<span class="dv">300</span>,<span class="dv">350</span>,<span class="dv">400</span>))<span class="sc">+</span></span>
<span id="cb95-9"><a href="#cb95-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">" Average Die Size (mm^2) Over Years"</span>, <span class="at">x =</span> <span class="st">"Release Date"</span>, <span class="at">y =</span> <span class="st">"Die Size (mm^2)"</span>) <span class="sc">+</span></span>
<span id="cb95-10"><a href="#cb95-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Project_Faisal_Saimeh_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div data-align="justify">
<p>This chart shows us an upward trend in the size of the Die for both CPU and GPU, unless in 2008 there was a decrease in size for the Die Size for CPU, but then returned to an upward trend with the GPU. The big change started in 2015 when each type took its own curve. The Die Size for the GPU started increasing, unlike the Die Size for the CPU, when started to decrease. GPU takes the opposite path of what we said before, that smaller Die Sizes allow for more Transistors resulting in higher processing power also consuming less power. There is another factor number and density of Transistors packed into the Die determine the processor’s computational capacity.</p>
</div>
</section>
<section id="average-tdp" class="level3">
<h3 class="anchored" data-anchor-id="average-tdp"><strong>Average TDP</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>result5 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(<span class="at">Year =</span> <span class="fu">as.numeric</span>(<span class="fu">format</span>(<span class="st">`</span><span class="at">Release Date</span><span class="st">`</span>, <span class="st">'%Y'</span>)), <span class="st">`</span><span class="at">TDP (W)</span><span class="st">`</span>, Type) <span class="sc">%&gt;%</span></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Type) <span class="sc">%&gt;%</span></span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_count =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">TDP (W)</span><span class="st">`</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Year'. You can override using the
`.groups` argument.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(result5, <span class="fu">aes</span>(<span class="at">x =</span>Year, <span class="at">y =</span> mean_count, <span class="at">color =</span> Type)) <span class="sc">+</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#0a75ad"</span>,<span class="st">"#ff4040"</span>)) <span class="sc">+</span></span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(</span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">2000</span>,<span class="dv">2002</span>,<span class="dv">2004</span>,<span class="dv">2006</span>,<span class="dv">2008</span>,<span class="dv">2010</span>,<span class="dv">2012</span>,<span class="dv">2014</span>,<span class="dv">2016</span>,<span class="dv">2018</span>,<span class="dv">2020</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="dv">2000</span>,<span class="dv">2002</span>,<span class="dv">2004</span>,<span class="dv">2006</span>,<span class="dv">2008</span>,<span class="dv">2010</span>,<span class="dv">2012</span>,<span class="dv">2014</span>,<span class="dv">2016</span>,<span class="dv">2018</span>,<span class="dv">2020</span>))<span class="sc">+</span></span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb98-8"><a href="#cb98-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">30</span>,<span class="dv">60</span>,<span class="dv">90</span>,<span class="dv">120</span>,<span class="dv">150</span>,<span class="dv">170</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="dv">30</span>,<span class="dv">60</span>,<span class="dv">90</span>,<span class="dv">120</span>,<span class="dv">150</span>,<span class="dv">170</span>))<span class="sc">+</span></span>
<span id="cb98-9"><a href="#cb98-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">" Average TDP (W) Over Years"</span>, <span class="at">x =</span> <span class="st">"Release Date"</span>, <span class="at">y =</span> <span class="st">"TDP (W)"</span>)<span class="sc">+</span></span>
<span id="cb98-10"><a href="#cb98-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Project_Faisal_Saimeh_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div data-align="justify">
<p>The TDP(W) started to increase slightly for both CPU and GPU, but after 2006, the gap between them has become large. GPU increased in TDP, but on the other hand the TDP of CPUs decreased until 2009, then started to increase to reach the GPU again in 2016. The huge jump happened in 2021 when the CPU became higher than the GPU. The TDP numbers are affected by several factors, but the most important are the Die Size and the Transistor performance measured by Frequency.</p>
</div>
</section>
<section id="average-transistor-density-with-frequency-and-tdp" class="level3">
<h3 class="anchored" data-anchor-id="average-transistor-density-with-frequency-and-tdp"><strong>Average Transistor Density with Frequency and TDP</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>result6 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(<span class="at">Year =</span> <span class="fu">as.numeric</span>(<span class="fu">format</span>(<span class="st">`</span><span class="at">Release Date</span><span class="st">`</span>, <span class="st">'%Y'</span>)), <span class="st">`</span><span class="at">Transistor Density</span><span class="st">`</span>, Type, <span class="st">`</span><span class="at">TDP (W)</span><span class="st">`</span>, <span class="st">`</span><span class="at">Frequency (GHz)</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Type) <span class="sc">%&gt;%</span></span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_transistor_density =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Transistor Density</span><span class="st">`</span>),</span>
<span id="cb99-6"><a href="#cb99-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_TDP_W =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">TDP (W)</span><span class="st">`</span>),</span>
<span id="cb99-7"><a href="#cb99-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_frequency_GHz =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Frequency (GHz)</span><span class="st">`</span>)</span>
<span id="cb99-8"><a href="#cb99-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Year'. You can override using the
`.groups` argument.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(result6, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> mean_transistor_density<span class="sc">/</span><span class="dv">1000000</span>, <span class="at">color =</span> mean_TDP_W, <span class="at">size =</span> mean_frequency_GHz)) <span class="sc">+</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Type) <span class="sc">+</span></span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_gradient</span>(<span class="at">low =</span> <span class="st">"blue"</span>, <span class="at">high =</span> <span class="st">"red"</span>, <span class="at">guide =</span> <span class="fu">guide_legend</span>(<span class="at">override.aes =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="dv">4</span>))) <span class="sc">+</span>  </span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb101-7"><a href="#cb101-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Transistor Density, Frequency (GHz) and TDP (W) Over Time by Type"</span>,</span>
<span id="cb101-8"><a href="#cb101-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>, </span>
<span id="cb101-9"><a href="#cb101-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Average Transistor Density (million)"</span>,</span>
<span id="cb101-10"><a href="#cb101-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Average TDP (W)"</span>, </span>
<span id="cb101-11"><a href="#cb101-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">size =</span> <span class="st">"Average Frequency (GHz)"</span>) <span class="sc">+</span></span>
<span id="cb101-12"><a href="#cb101-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">size =</span> <span class="fu">guide_legend</span>(<span class="st">"Average Frequency (GHz)"</span>)) <span class="sc">+</span></span>
<span id="cb101-13"><a href="#cb101-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_gray</span>() <span class="sc">+</span> </span>
<span id="cb101-14"><a href="#cb101-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb101-15"><a href="#cb101-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>), </span>
<span id="cb101-16"><a href="#cb101-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">16</span>))<span class="sc">+</span></span>
<span id="cb101-17"><a href="#cb101-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Project_Faisal_Saimeh_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid" width="1056"></p>
</div>
</div>
<div data-align="justify">
<p>As we can see, the Transistor Density can affect Frequency, TDP (W), or both. Over the years these two processors have evolved to generate the best performance with the best power consumption. Often one feature is developed over another. For example, we see some pieces developed in terms of power at the expense of energy consumption and vice versa. Some products evolved in both energy and performance but did not reach the peak of the products that evolved from one side, but I believe they are the best option as they give everything balanced in terms of performance and energy consumption. We also notice a clear superiority of the CPU over the GPU in terms of performance and energy consumption in general. In recent years, there has been a convergence between processors, and in particular, the GPU is developing steadily so that it is approaching the CPU and may pass it in the future.</p>
</div>
</section>
<section id="average-transistor-density-with-frequency-and-tdp-2.2-2.3-ghz" class="level3">
<h3 class="anchored" data-anchor-id="average-transistor-density-with-frequency-and-tdp-2.2-2.3-ghz"><strong>Average Transistor Density with Frequency and TDP (2.2 &amp; 2.3 GHz)</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>result7 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Frequency (GHz)</span><span class="st">`</span> <span class="sc">==</span> <span class="fl">2.3</span> <span class="sc">|</span> <span class="st">`</span><span class="at">Frequency (GHz)</span><span class="st">`</span> <span class="sc">==</span> <span class="fl">2.2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(<span class="at">Year =</span> <span class="fu">as.numeric</span>(<span class="fu">format</span>(<span class="st">`</span><span class="at">Release Date</span><span class="st">`</span>, <span class="st">'%Y'</span>)), <span class="st">`</span><span class="at">Transistor Density</span><span class="st">`</span>, Type, <span class="st">`</span><span class="at">TDP (W)</span><span class="st">`</span>, <span class="st">`</span><span class="at">Frequency (GHz)</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Type) <span class="sc">%&gt;%</span></span>
<span id="cb102-5"><a href="#cb102-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb102-6"><a href="#cb102-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_transistor_density =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Transistor Density</span><span class="st">`</span>),</span>
<span id="cb102-7"><a href="#cb102-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_TDP_W =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">TDP (W)</span><span class="st">`</span>),</span>
<span id="cb102-8"><a href="#cb102-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_frequency_GHz =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Frequency (GHz)</span><span class="st">`</span>)</span>
<span id="cb102-9"><a href="#cb102-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Year'. You can override using the
`.groups` argument.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(result7, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> mean_transistor_density<span class="sc">/</span><span class="dv">1000000</span>, <span class="at">color =</span> mean_TDP_W, <span class="at">size =</span> mean_frequency_GHz)) <span class="sc">+</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Type) <span class="sc">+</span></span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_gradient</span>(<span class="at">low =</span> <span class="st">"blue"</span>, <span class="at">high =</span> <span class="st">"red"</span>, <span class="at">guide =</span> <span class="fu">guide_legend</span>(<span class="at">override.aes =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="dv">5</span>))) <span class="sc">+</span>  </span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb104-6"><a href="#cb104-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb104-7"><a href="#cb104-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Transistor Density, Frequency (GHz) and TDP (W) Over Time by Type"</span>,</span>
<span id="cb104-8"><a href="#cb104-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>, </span>
<span id="cb104-9"><a href="#cb104-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Average Transistor Density (million)"</span>,</span>
<span id="cb104-10"><a href="#cb104-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Average TDP (W)"</span>, </span>
<span id="cb104-11"><a href="#cb104-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">size =</span> <span class="st">"Average Frequency (GHz)"</span>) <span class="sc">+</span></span>
<span id="cb104-12"><a href="#cb104-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">size =</span> <span class="fu">guide_legend</span>(<span class="st">"Average Frequency (GHz)"</span>)) <span class="sc">+</span></span>
<span id="cb104-13"><a href="#cb104-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_gray</span>() <span class="sc">+</span></span>
<span id="cb104-14"><a href="#cb104-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb104-15"><a href="#cb104-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>), </span>
<span id="cb104-16"><a href="#cb104-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">16</span>))<span class="sc">+</span></span>
<span id="cb104-17"><a href="#cb104-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Project_Faisal_Saimeh_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid" width="1056"></p>
</div>
</div>
<div data-align="justify">
<p>This graph shows only average frequencies of 2.2 and 2.3 GHz to clarify how GPU evolved and kind of reached the CPU performance and power consumption through these years, yes still CPU taking over in general but it is considered a huge jump for the GPU.</p>
<p><strong>Note:</strong></p>
<p>I chose only these two numbers because it is the highest number that GPU has reached in this period compared with CPU reached higher than but to compare these two processors and to follow the evolution of GPU compared to CPU.</p>
</div>
</section>
</section>
<section id="comparison-between-companies-over-years" class="level2">
<h2 class="anchored" data-anchor-id="comparison-between-companies-over-years"><strong>Comparison Between Companies Over Years</strong></h2>
<section id="processors-count-between-companies" class="level3">
<h3 class="anchored" data-anchor-id="processors-count-between-companies"><strong>Processors Count between Companies</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>data_for_plot2 <span class="ot">=</span>  data <span class="sc">%&gt;%</span> <span class="fu">count</span>(Type,Company,<span class="at">name=</span><span class="st">"Count"</span>)</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_for_plot2,<span class="fu">aes</span>(<span class="at">x=</span>Company, <span class="at">y=</span>Count,<span class="at">fill=</span> Type),<span class="at">fill =</span> Type) <span class="sc">+</span> </span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Count),<span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="dv">1</span>), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position=</span><span class="st">'dodge'</span>, <span class="at">stat=</span><span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb105-5"><a href="#cb105-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb105-6"><a href="#cb105-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">500</span>,<span class="dv">1000</span>,<span class="dv">1500</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="dv">500</span>,<span class="dv">1000</span>,<span class="dv">1500</span>)) <span class="sc">+</span></span>
<span id="cb105-7"><a href="#cb105-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">"#ffa500"</span>, <span class="st">"#0a75ad"</span>),<span class="at">labels =</span> legend_labels)<span class="sc">+</span></span>
<span id="cb105-8"><a href="#cb105-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"CPU and GPU Count between Companies"</span>) <span class="sc">+</span></span>
<span id="cb105-9"><a href="#cb105-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb105-10"><a href="#cb105-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"right"</span>, <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Project_Faisal_Saimeh_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div data-align="justify">
<p>This graph shows us the numbers of CPU and GPU between companies. As we can see, there are two companies (AMD, Intel) manufacturing CPU and GPU, the others manufacturing only GPU. After looking at this graph, we see Intel and Nvidia taking the lead in making processors, Intel in CPU, and Nvidia in GPU, and there is AMD which I consider also a competitor for these companies because it comes as number two after Intel in CPU manufacturing and number two after NVIDIA in GPU manufacturing.</p>
</div>
</section>
<section id="distribution-of-product-types-by-company" class="level3">
<h3 class="anchored" data-anchor-id="distribution-of-product-types-by-company"><strong>Distribution of Product Types by Company</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Year <span class="ot">&lt;-</span> <span class="fu">year</span>(<span class="fu">ymd</span>(data<span class="sc">$</span><span class="st">`</span><span class="at">Release Date</span><span class="st">`</span>))</span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a>visualization_data1 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb106-4"><a href="#cb106-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Company, Type) <span class="sc">%&gt;%</span></span>
<span id="cb106-5"><a href="#cb106-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Count =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">'drop'</span>)</span>
<span id="cb106-6"><a href="#cb106-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-7"><a href="#cb106-7" aria-hidden="true" tabindex="-1"></a>my_colors1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"AMD"</span> <span class="ot">=</span> <span class="st">"#ff4d00"</span>, <span class="st">"ATI"</span> <span class="ot">=</span> <span class="st">"#e10000"</span>, <span class="st">"Intel"</span> <span class="ot">=</span> <span class="st">"#1f77b4"</span>,<span class="st">"NVIDIA"</span><span class="ot">=</span><span class="st">"#2ca02c"</span> ,<span class="st">"Other"</span><span class="ot">=</span><span class="st">"#660066"</span>)</span>
<span id="cb106-8"><a href="#cb106-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-9"><a href="#cb106-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(visualization_data1, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Count, <span class="at">fill =</span> Company)) <span class="sc">+</span></span>
<span id="cb106-10"><a href="#cb106-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>() <span class="sc">+</span></span>
<span id="cb106-11"><a href="#cb106-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Type)<span class="sc">+</span></span>
<span id="cb106-12"><a href="#cb106-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> my_colors1) <span class="sc">+</span></span>
<span id="cb106-13"><a href="#cb106-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Product Types by Company Over the Years"</span>,</span>
<span id="cb106-14"><a href="#cb106-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Number of Products Released"</span>) <span class="sc">+</span></span>
<span id="cb106-15"><a href="#cb106-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">theme_gray</span>()<span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Project_Faisal_Saimeh_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div data-align="justify">
<p>In this graph, we delve deeper into analyzing companies over the years on several productions released. As we can see in the GPU graph three companies still produce processors Intel, Nvidia, and AMD which entered the field of GPU in 2006, unlike ATI and other companies that stop producing. Nvidia and AMD are sweeping the market with graphics card products. As for Intel, its numbers are very modest compared to the two companies, but it is continuing to manufacture. In the CPU graph, we have only two companies Intel and AMD with simple superiority for Intel. As we see in the period between 2016 and 2017, we notice a clear decline for the two companies. After research, the reasons for the decline were revealed:</p>
<ul>
<li><p>Intel faced a significant delay in transitioning to its 10 nm CPU production, originally scheduled for the second half of 2016 but postponed to 2019. This delay was due to yield issues and challenges with multi-patterning, a semiconductor fabrication technique. As a result of these difficulties, which marked one of the hardest transitions in Intel’s history, the company had to extend its reliance on the older 14 nm process technology for a longer duration than initially planned.</p></li>
<li><p>On the other hand, AMD faced in the fourth quarter of 2016, experienced an operating loss mainly due to increased stock-based compensation charges. During this time, AMD was actively developing and announcing new CPU and GPU technologies, particularly their “Zen”-based processors like Ryzen and products using the Vega GPU architecture. They also engaged in significant collaborations and initiatives, including partnering with Google for Radeon GPU technology and launching the Radeon Instinct initiative for deep learning and high-performance computing. Despite these developments and expansions into new areas, AMD faced financial challenges in the market at this time.</p></li>
</ul>
</div>
</section>
<section id="average-frequency-ghz-by-company" class="level3">
<h3 class="anchored" data-anchor-id="average-frequency-ghz-by-company"><strong>Average Frequency (GHz) by Company</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>filtered_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Company <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Intel"</span>, <span class="st">"NVIDIA"</span>, <span class="st">"AMD"</span>))</span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-4"><a href="#cb107-4" aria-hidden="true" tabindex="-1"></a>visualization_data2 <span class="ot">&lt;-</span> filtered_data <span class="sc">%&gt;%</span></span>
<span id="cb107-5"><a href="#cb107-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Company,Type) <span class="sc">%&gt;%</span></span>
<span id="cb107-6"><a href="#cb107-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">AvgFrequency =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Frequency (GHz)</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">'drop'</span>)</span>
<span id="cb107-7"><a href="#cb107-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-8"><a href="#cb107-8" aria-hidden="true" tabindex="-1"></a>my_colors2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"AMD"</span> <span class="ot">=</span> <span class="st">"#ff4d00"</span>,<span class="st">"Intel"</span> <span class="ot">=</span> <span class="st">"#1f77b4"</span>,<span class="st">"NVIDIA"</span><span class="ot">=</span><span class="st">"#2ca02c"</span>)</span>
<span id="cb107-9"><a href="#cb107-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-10"><a href="#cb107-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(visualization_data2, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> AvgFrequency, <span class="at">color =</span> Company)) <span class="sc">+</span></span>
<span id="cb107-11"><a href="#cb107-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb107-12"><a href="#cb107-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb107-13"><a href="#cb107-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> my_colors2)<span class="sc">+</span></span>
<span id="cb107-14"><a href="#cb107-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Type)<span class="sc">+</span></span>
<span id="cb107-15"><a href="#cb107-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Frequency (GHz) Over the Years by Company"</span>,</span>
<span id="cb107-16"><a href="#cb107-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Average Frequency (GHz)"</span>) <span class="sc">+</span></span>
<span id="cb107-17"><a href="#cb107-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb107-18"><a href="#cb107-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)<span class="sc">+</span><span class="fu">theme_gray</span>() <span class="sc">+</span><span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">1</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Project_Faisal_Saimeh_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div data-align="justify">
<p><strong>CPU Trends:</strong></p>
<p>Both AMD and Intel have been fluctuating in terms of average CPU frequency over the years. AMD’s frequency started below Intel’s, surpassed it around 2005, then saw a decline and fluctuated afterwards with an increasing trend up until the last data point. Intel’s frequency increased until about 2005, declined sharply, and then fluctuated with what seems to be a slight downward trend towards the end of the period.</p>
<p><strong>GPU Trends:</strong></p>
<p>NVIDIA shows a consistent increase in GPU frequency from 2000 until around 2015, after which it fluctuates but appears to have an overall slight upward trend. AMD’s GPU data starts around 2006, significantly later than Intel and NVIDIA. Although it is has entered the GPU market later, it beats Intel GPU and considered strong competitor for NVIDIA. Intel’s frequency shows an increasing trend but remains below that of NVIDIA and AMD.</p>
</div>
</section>
<section id="average-transistor-density-by-company" class="level3">
<h3 class="anchored" data-anchor-id="average-transistor-density-by-company"><strong>Average Transistor Density by Company</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>visualization_data3 <span class="ot">&lt;-</span> filtered_data <span class="sc">%&gt;%</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, Company,Type) <span class="sc">%&gt;%</span></span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">AvgTransistorDensity =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Transistor Density</span><span class="st">`</span><span class="sc">/</span><span class="dv">1000000</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">'drop'</span>)</span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-5"><a href="#cb108-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(visualization_data3, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> AvgTransistorDensity, <span class="at">color =</span> Company)) <span class="sc">+</span></span>
<span id="cb108-6"><a href="#cb108-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb108-7"><a href="#cb108-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb108-8"><a href="#cb108-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> my_colors2)<span class="sc">+</span></span>
<span id="cb108-9"><a href="#cb108-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Type)<span class="sc">+</span></span>
<span id="cb108-10"><a href="#cb108-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Transistor Density Over the Years by Company"</span>,</span>
<span id="cb108-11"><a href="#cb108-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Average Transistor Density (million)"</span>) <span class="sc">+</span></span>
<span id="cb108-12"><a href="#cb108-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb108-13"><a href="#cb108-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>) <span class="sc">+</span> <span class="fu">theme_gray</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Project_Faisal_Saimeh_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div data-align="justify">
<p><strong>CPU Trends:</strong></p>
<ul>
<li><p>AMD: There are significant fluctuations in AMD’s transistor density for CPUs. It peaked twice, the first time around 2005, and the trend appears to be steadily increasing, the second peak was sharply around 2019 then dropped in the next years.</p></li>
<li><p>Intel: Intel’s curve is somewhat smoother than AMD’s, with a gradual increase over time. There is a noticeable jump around 2016, then a big dip in the next year. However, the overall trend is upward, showing a consistent improvement in transistor density.</p></li>
</ul>
<p><strong>GPU Trends:</strong></p>
<ul>
<li><p>AMD: leads the GPU transistor density race, starting higher than NVIDIA and after time crossing Intel and maintaining its lead throughout the years. The curve for AMD shows a very steep increase starting from around 2015, indicating a rapid improvement in their GPU transistor density. Around 2015, AMD’s density surpassed Intel’s and closely approached NVIDIA’s, indicating significant progress in this period. In 2020 AMD passed NVIDIA.</p></li>
<li><p>Intel: The trend line for Intel shows a consistent but in the period from 2007 to 2013 there were significant fluctuations in Intel’s transistor density, then the trend appears to be steadily increasing, but still less than AMD and NVIDIA.</p></li>
<li><p>NVIDIA: The trend for NVIDIA GPU transistor density starts lower than Intel’s but sees a steady increase over time and beats Intel. The direct competitor for NVIDIA is AMD, but AMD has outperformed.</p></li>
</ul>
</div>
</section>
</section>
</section>
<section id="insights-and-conclusion" class="level1">
<h1>Insights and Conclusion</h1>
<div data-align="justify">
<p>After thorough extensive and insightful exploration data analysis with the CPU and GPU products plus the competitor companies’ dataset, we have now concluded our exploration. We have discovered various concepts and observations that are interesting, and we’ll summarize what we have learned about our dataset.</p>
<p>In our initial analysis, we can recognize that the CPU beat the GPU in process size, frequency, die size, and TDP unlike the GPU beat the CPU in the number of transistors and of course transistor density. This means that the CPU is more powerful and more developed in general than the GPU but that does not it can beat it in every field, in our project we focused on which of these processors is more powerful for machine learning, and in this case, the GPU is the winner. As we mentioned before GPUs have more transistors than CPUs due to their different architectures. CPUs have fewer but more powerful and complex cores, capable of handling a wide range of tasks and complex processes. In contrast, GPUs are designed for parallel computing, making them highly efficient for tasks like graphics rendering and machine learning workloads, which require processing large amounts of data simultaneously. This focus on parallel processing is why GPUs are more powerful for machine learning applications. We also got to know that some GPUs reached the frequency of the CPUs from 2020 which gives an indication maybe in the future the GPU is going to beat the CPU frequency, of course, will not be dispensed of the CPU but the GPU will be used in more fields than machine learning.</p>
<p>Then analyzing processors between companies, we got that there are three giant companies compete each other and they are Intel, NVIDIA, and AMD. The two companies Intel and AMD compete on both types of processors despite the superiority of Intel in CPU over AMD but in GPU her presence is very weak compared to AMD which is facing NVIDIA which is considered the direct competitor in GPU.</p>
<p>Lastly, the trends in CPU and GPU frequencies and transistor densities of AMD, Intel, and NVIDIA over time. AMD initially trailed in CPU frequency but overtook Intel in 2005 and showed a generally increasing trend despite some fluctuations. Intel’s CPU frequency peaked around 2005, then decreased with minor fluctuations. NVIDIA’s GPU frequency consistently rose until 2015, then fluctuated but still trended upward. AMD joined the GPU market later but soon outperformed Intel and challenged NVIDIA. Intel’s GPU frequencies, though increasing, stayed below those of its competitors. For CPU transistor density, AMD saw significant variations, peaking around 2005 and 2019 with an overall upward trend. Intel experienced a steady rise with a notable increase in 2016, followed by a slight decline. In GPU transistor density, AMD led by surpassing Intel and eventually NVIDIA in 2020 after a sharp rise from 2015. Intel’s GPU density, while improving, lagged behind others. NVIDIA’s GPU density started behind Intel but steadily grew, although AMD eventually outpaced it.</p>
</div>
</section>
<section id="references" class="level1">
<h1>References</h1>
<div data-align="justify">
<ul>
<li>Tim Dettmers</li>
</ul>
<p><a href="https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/" class="uri">https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/</a></p>
<ul>
<li>Ace Cloud</li>
</ul>
<p><a href="https://www.acecloudhosting.com/blog/gpu-vs-cpu-for-data-analytics-tasks/#GPU_Vs_CPU_for_Data_Analytics_Which_One_is_Best_for_Your_Needs" class="uri">https://www.acecloudhosting.com/blog/gpu-vs-cpu-for-data-analytics-tasks/#GPU_Vs_CPU_for_Data_Analytics_Which_One_is_Best_for_Your_Needs</a></p>
<ul>
<li>AnandTech</li>
</ul>
<p><a href="https://www.anandtech.com/show/12693/intel-delays-mass-production-of-10-nm-cpus-to-2019" class="uri">https://www.anandtech.com/show/12693/intel-delays-mass-production-of-10-nm-cpus-to-2019</a></p>
<ul>
<li>AMD Investor Relations</li>
</ul>
<p><a href="https://ir.amd.com/news-events/press-releases/detail/746/amd-reports-fourth-quarter-and-annual-2016-financial-results" class="uri">https://ir.amd.com/news-events/press-releases/detail/746/amd-reports-fourth-quarter-and-annual-2016-financial-results</a></p>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>